[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/login.html"
  status = 302
  force = true
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/admin/dashboard"
  to = "/admin/dashboard.html"
  status = 302
  force = true
  conditions = {Role = ["admin"]}

[build.environment]
  NODE_VERSION = "16"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:;" 